LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 256
NUM_EPOCHS : 30
LINEAR_PROBING: False
PROBING_EPOCHS : 30
PATIENCE : 10

IMAGE_SIZE : 224

MODEL: ResNet18
PRETRAINED: False
LOSS: CrossEntropyLoss

LR_RATE_LIST: [3e-4 , 1e-4 , 3e-5 , 1e-5]
NUM_EPOCHS_LIST: [15, 20, 25]
AUGMENT_LIST: [Minimal, Medium, Heavy]

