LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 256
NUM_EPOCHS : 30
LINEAR_PROBING: False
PROBING_EPOCHS : 30
PATIENCE : 10

IMAGE_SIZE : 224


MODEL: ResNet18
PRETRAINED: False
LOSS: CrossEntropyLoss

CUDA_DEVICE: 0

RUN_NAME: "2023-12-26_18-28-36"

LR_RATE_LIST: [3e-4 , 1e-4, 3e-5 , 1e-5]
NUM_EPOCHS_MINIMAL: [15, 20, 25]
NUM_EPOCHS_MEDIUM: [25, 30, 35]
NUM_EPOCHS_HEAVY: [35, 40, 45]

AUGMENT_LIST: [Minimal, Medium, Heavy]

datasets: &DATASET_OPTIONS
  - &CIFAR Cifar
  - &RSNA Rsna

NUM_CLASSES: 10 #2 for RSNA, 10 for CIFAR
DATASET: *CIFAR

RSNA_PATH: "dataset/rsna_18"

RSNA_CSV: "dataset/rsna_18/csv/final_dataset_wo_not_normal_cases.csv"

#source /share/sda/nurenzhaksylyk/SEGA2023/SegaAlgorithm/sega/bin/activate

