BATCH_SIZE : 128
NUM_WORKERS : 16
LINEAR_PROBING: False
PROBING_EPOCHS : 30
PATIENCE : 5

IMAGE_SIZE : 224


PRETRAINED: False
LOSS: CrossEntropyLoss

# RUN_NAME: "2023-12-26_21-49-40" #RSNA


LR_RATE_LIST: [1e-4, 5e-5, 1e-5, 5e-6, 1e-6, 5e-3, 1e-3, 5e-2, 1e-2]

datasets: &DATASET_OPTIONS
  - &CIFAR10 Cifar10
  - &CIFAR100 Cifar100
  - &RSNA Rsna
  - &HAM HAM
  - &APTOS APTOS
  - &DR DR
  - &MIMIC MIMIC


RSNA_PATH: "./dataset/rsna18"
CIFAR_PATH: "./dataset/cifar"
CIFAR_INDICES: "./dataset/cifar/cifar1098_idxs.npy"
RSNA_CSV: "./dataset/rsna18/csv/final_dataset_wo_not_normal_cases.csv"
HAM_TRAIN_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Training_Input/"
HAM_VAL_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Validation_Input/"
HAM_TEST_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Test_Input/"
HAM_TRAIN_CSV : "./dataset/ISIC/ISIC2018_Task3_Training_GroundTruth/ISIC2018_Task3_Training_GroundTruth.csv"
HAM_VAL_CSV : "./dataset/ISIC/ISIC2018_Task3_Validation_GroundTruth/ISIC2018_Task3_Validation_GroundTruth.csv"
HAM_TEST_CSV : "./dataset/ISIC/ISIC2018_Task3_Test_GroundTruth/ISIC2018_Task3_Test_GroundTruth.csv"
APTOS_FOLDER: "./dataset/224_data/DR/aptos/"
APTOS_CSV: "./dataset/224_data/DR/aptos/aptos_dataset_splits.csv"
#source /share/sda/nurenzhaksylyk/SEGA2023/SegaAlgorithm/sega/bin/activate
paths: &PATH_OPTIONS
  - &CIFAR_PATH ./dataset/cifar""./dataset/cifar/cifar1098_idxs.npy
  - &RSNA_PATH ./dataset/rsna18""./dataset/rsna18/csv/final_dataset_wo_not_normal_cases.csv
  - &HAM_PATH ./dataset/ISIC/ISIC2018_Task3_Training_Input/""./dataset/ISIC/ISIC2018_Task3_Validation_Input/""./dataset/ISIC/ISIC2018_Task3_Test_Input/""./dataset/ISIC/ISIC2018_Task3_Training_GroundTruth/ISIC2018_Task3_Training_GroundTruth.csv""./dataset/ISIC/ISIC2018_Task3_Validation_GroundTruth/ISIC2018_Task3_Validation_GroundTruth.csv""./dataset/ISIC/ISIC2018_Task3_Test_GroundTruth/ISIC2018_Task3_Test_GroundTruth.csv
  - &DR_PATH ./dataset/224_data/DR/""./dataset/224_data/DR/all_dataset_splits.csv
  - &APTOS_PATH ./dataset/224_data/DR/aptos/""./dataset/224_data/DR/aptos/aptos_dataset_splits.csv
  - &MIMIC_PATH ./dataset/MIMIC/files/mimic-cxr-jpg/2.0.0/files/""./dataset/MIMIC/files/mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-chexpert.csv""./dataset/MIMIC/files/mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-metadata.csv""./dataset/MIMIC/files/mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-split.csv
  
######CHANGE ONLY THIS#########
NUM_EPOCHS : 200
TASK: Classification
INITIALISATION: Random
PRETRAINING: Random
LEARNING_SCHEDULER : CosineAnnealingLR
SAVE_DIR: "./runs/san_final_hyp_models/san-intialisation/MIMIC_model/resnet50/"
CUDA_DEVICE: 0
NUM_CLASSES: 5 #2 for RSNA, 10 for CIFAR
DATASET: *MIMIC
MODEL: ResNet50
PATH: *MIMIC_PATH
RESUME_PATH: ""
#source /share/sda/nurenzhaksylyk/SEGA2023/SegaAlgorithm/sega/bin/activate

