LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 128
NUM_EPOCHS : 10
LINEAR_PROBING: False
PROBING_EPOCHS : 30
PATIENCE : 10



PRETRAINED: True
LOSS: CrossEntropyLoss


datasets: &DATASET_OPTIONS
  - &CIFAR10 Cifar10
  - &CIFAR100 Cifar100
  - &RSNA Rsna
  - &HAM HAM
  - &APTOS APTOS



CIFAR_PATH: "./dataset/cifar"
CIFAR_INDICES: "./dataset/cifar/cifar1098_idxs.npy"
RSNA_PATH: "./dataset/rsna18/"
RSNA_CSV: "./dataset/rsna18/csv/final_dataset_wo_not_normal_cases.csv"
HAM_TRAIN_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Training_Input/"
HAM_VAL_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Validation_Input/"
HAM_TEST_FOLDER : "./dataset/ISIC/ISIC2018_Task3_Test_Input/"
HAM_TRAIN_CSV : "./dataset/ISIC/ISIC2018_Task3_Training_GroundTruth/ISIC2018_Task3_Training_GroundTruth.csv"
HAM_VAL_CSV : "./dataset/ISIC/ISIC2018_Task3_Validation_GroundTruth/ISIC2018_Task3_Validation_GroundTruth.csv"
HAM_TEST_CSV : "./dataset/ISIC/ISIC2018_Task3_Test_GroundTruth/ISIC2018_Task3_Test_GroundTruth.csv"
APTOS_FOLDER: "./dataset/224_data/DR/aptos/"
APTOS_CSV: "./dataset/224_data/DR/aptos/aptos_dataset_splits.csv"

######CHANGE ONLY THIS#######
MODEL: DeiT-S
PRETRAINING: ImageNet
LEARNING_RATE : 1e-3
IMAGE_SIZE : 224
CUDA_DEVICE: 0
NUM_CLASSES: 5 #2 for RSNA, 10 for CIFAR
DATASET: *APTOS
SAVE_DIR: "./runs/san_final_hyp_models/san-initial_models/aptos_final_hyp/deitS_imagenet/"
#source /share/sda/nurenzhaksylyk/SEGA2023/SegaAlgorithm/sega/bin/activate
