LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 128
NUM_EPOCHS : 10
LINEAR_PROBING: False
PROBING_EPOCHS : 30
PATIENCE : 4

IMAGE_SIZE : 224


PRETRAINED: True
LOSS: CrossEntropyLoss


datasets: &DATASET_OPTIONS
  - &CIFAR10 Cifar10
  - &CIFAR100 Cifar100
  - &RSNA Rsna



CIFAR_PATH: "./dataset/cifar"
CIFAR_INDICES: "./dataset/cifar/cifar1098_idxs.npy"
RSNA_PATH: "dataset/rsna_18"
RSNA_CSV: "dataset/rsna_18/csv/final_dataset_wo_not_normal_cases.csv"


######CHANGE ONLY THIS#######
MODEL: DenseNet121
CUDA_DEVICE: 0
NUM_CLASSES: 10 #2 for RSNA, 10 for CIFAR
DATASET: *CIFAR10
SAVE_DIR: "./runs/san_final_hyp_models/san-initial_models/cifar_final_hyp/densenet-121/"
#source /share/sda/nurenzhaksylyk/SEGA2023/SegaAlgorithm/sega/bin/activate
